apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: strimzi
spec:
  name: ${OLM_OPERATOR_NAME}
  source: strimzi-source
  sourceNamespace: openshift-marketplace
  startingCSV: ${OLM_APP_BUNDLE_PREFIX}.${OLM_OPERATOR_VERSION}
  channel: stable
  installPlanApproval: Automatic
